version: "{build}"

platform: x64

clone_folder: c:\gopath\src\com.github\census-instrumentation\opencensus-service

environment:
  GOPATH: 'c:\gopath'
  GOVERSION: '1.11'
  GO111MODULE: 'on'
  CGO_ENABLED: '0' # See: https://github.com/appveyor/ci/issues/2613

install:
  - choco install make
  - choco install bzr
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\Program Files (x86)\Bazaar\;%PATH%
  - go version
  - go env
  
build: false
deploy: false

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %cd%
  - make install-tools
  - go build -v .\...
  - go test -v .\... # No -race because cgo is disabled

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))