version: "{build}"

platform: x64

clone_folder: c:\gopath\src\com.github\census-instrumentation\opencensus-service

environment:
  GOPATH: 'c:\gopath'
  GOVERSION: '1.11'
  GO111MODULE: 'on'
  CGO_ENABLED: '0' # See: https://github.com/appveyor/ci/issues/2613
  GOTEST_OPT: '-v -timeout 30s' # No -race because cgo is disabled

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - choco install make

build: false
deploy: false

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - make install-tools
  - make
