receivers:
  opencensus:
    endpoint: "localhost:50001"

  zipkin:
    port: 9410

  jaeger:
    collector_thrift_port: 14277
    collector_http_port: 14278

exporters:

  opencensus:
    endpoint: "localhost:10001"

